#!/usr/bin/env bash
# Generate D2 diagram from Go package dependencies
# Usage: ./gen-deps.sh [beads_repo_path]
# Requires: bash 4+, go, d2

set -euo pipefail

BEADS_ROOT="${1:-/Volumes/atlas/beads}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/../diagrams"
GENERATED_DIR="${OUTPUT_DIR}/generated"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log() { echo -e "${BLUE}[gen-deps]${NC} $1"; }
success() { echo -e "${GREEN}[gen-deps]${NC} $1"; }
error() { echo -e "${RED}[gen-deps]${NC} $1" >&2; }

# Verify beads repo exists
if [[ ! -d "${BEADS_ROOT}/internal" ]]; then
    error "Beads repo not found at ${BEADS_ROOT}"
    error "Usage: $0 [beads_repo_path]"
    exit 1
fi

# Ensure output directories exist
mkdir -p "${GENERATED_DIR}"

log "Analyzing packages in ${BEADS_ROOT}..."

# Function to get group for a package (portable version)
get_group() {
    local pkg="$1"
    case "$pkg" in
        storage|storage/*) echo "storage" ;;
        autoimport|importer|export|syncbranch) echo "sync" ;;
        git|merge) echo "git" ;;
        daemon|rpc|lockfile) echo "daemon" ;;
        types|beads|routing|idgen) echo "core" ;;
        molecules|compact|linear|hooks|formula|recipes|audit) echo "features" ;;
        config|configfile) echo "config" ;;
        testutil|testutil/*) echo "test" ;;
        *) echo "util" ;;
    esac
}

# Function to get color for a group
get_color() {
    local group="$1"
    case "$group" in
        storage) echo "#438dd5" ;;
        sync) echo "#81c784" ;;
        git) echo "#f48fb1" ;;
        daemon) echo "#ffb74d" ;;
        core) echo "#b39ddb" ;;
        features) echo "#4dd0e1" ;;
        config) echo "#fff176" ;;
        util) echo "#e0e0e0" ;;
        test) echo "#bcaaa4" ;;
        *) echo "#cccccc" ;;
    esac
}

# Generate D2 file header
D2_FILE="${OUTPUT_DIR}/package-deps.d2"
cat > "${D2_FILE}" << 'EOF'
# Auto-generated Package Dependency Diagram
# Generated by: scripts/gen-deps.sh
# DO NOT EDIT - regenerate with ./scripts/gen-deps.sh

title: {
  label: "Beads Internal Package Dependencies"
  near: top-center
  style: {
    font-size: 24
    bold: true
  }
}

direction: right

EOF

# Generate group containers
for group in storage sync git daemon core features config util; do
    color=$(get_color "$group")
    cat >> "${D2_FILE}" << EOF
${group}: "${group^} Layer" {
  style: {
    fill: "#f5f5f5"
    stroke: "${color}"
    stroke-width: 2
  }
}

EOF
done

log "Extracting package dependencies..."

# Track packages we've added
added_packages=""

# Get all internal packages and their internal dependencies
cd "${BEADS_ROOT}"

# First pass: add all packages to their groups
go list -f '{{.ImportPath}}' ./internal/... 2>/dev/null | while read -r pkg; do
    short_pkg="${pkg#github.com/steveyegge/beads/internal/}"
    [[ -z "$short_pkg" ]] && continue

    group=$(get_group "$short_pkg")
    d2_pkg="${short_pkg//\//_}"

    echo "${group}.${d2_pkg}: \"${short_pkg}\"" >> "${D2_FILE}"
done

echo "" >> "${D2_FILE}"
echo "# Dependencies" >> "${D2_FILE}"

# Second pass: add edges
go list -f '{{.ImportPath}}|{{join .Imports ","}}' ./internal/... 2>/dev/null | while IFS='|' read -r pkg imports; do
    short_pkg="${pkg#github.com/steveyegge/beads/internal/}"
    [[ -z "$short_pkg" ]] && continue

    group=$(get_group "$short_pkg")
    d2_pkg="${short_pkg//\//_}"

    if [[ -n "$imports" ]]; then
        IFS=',' read -ra deps <<< "$imports"
        for dep in "${deps[@]}"; do
            if [[ "$dep" == github.com/steveyegge/beads/internal/* ]]; then
                short_dep="${dep#github.com/steveyegge/beads/internal/}"
                dep_group=$(get_group "$short_dep")
                d2_dep="${short_dep//\//_}"

                if [[ "$d2_pkg" != "$d2_dep" ]]; then
                    echo "${group}.${d2_pkg} -> ${dep_group}.${d2_dep}" >> "${D2_FILE}"
                fi
            fi
        done
    fi
done

# Add legend
cat >> "${D2_FILE}" << 'EOF'

# Legend
legend: {
  near: bottom-left
  style: {
    fill: "#f5f5f5"
    stroke: "#cccccc"
  }

  storage_l: "Storage" { style.fill: "#438dd5"; width: 50; height: 20 }
  sync_l: "Sync" { style.fill: "#81c784"; width: 50; height: 20 }
  git_l: "Git" { style.fill: "#f48fb1"; width: 50; height: 20 }
  daemon_l: "Daemon" { style.fill: "#ffb74d"; width: 50; height: 20 }
  core_l: "Core" { style.fill: "#b39ddb"; width: 50; height: 20 }
  features_l: "Features" { style.fill: "#4dd0e1"; width: 50; height: 20 }
}
EOF

success "Generated ${D2_FILE}"

# Generate SVG
log "Rendering SVG..."
if command -v d2 &> /dev/null; then
    if d2 --theme=0 "${D2_FILE}" "${GENERATED_DIR}/package-deps.svg" 2>&1; then
        success "Generated ${GENERATED_DIR}/package-deps.svg"
    else
        error "D2 rendering failed - check ${D2_FILE} for syntax errors"
        exit 1
    fi
else
    error "d2 not found - install from https://d2lang.com"
    exit 1
fi

# Summary
log ""
log "Package analysis complete!"
log "  D2 source:  ${D2_FILE}"
log "  SVG output: ${GENERATED_DIR}/package-deps.svg"
log ""
log "To iterate: d2 --watch ${D2_FILE} ${GENERATED_DIR}/package-deps.svg"
